//image
var hero_rs = {
	h_m1 : "res/img/1.png",
	h_m2 : "res/img/2.png",
	h_m3 : "res/img/3.png",
	h_m4 : "res/img/4.png",
	h_m5 : "res/img/5.png",
	h_m6 : "res/img/6.png",
	h_p0 : "res/img/powers/0.png",
	h_p1 : "res/img/powers/1.png",
	h_p2 : "res/img/powers/2.png",
	h_p3 : "res/img/powers/3.png",
	h_p4 : "res/img/powers/4.png",
	h_p5 : "res/img/powers/5.png",
	h_p6 : "res/img/powers/6.png",
	h_p7 : "res/img/powers/7.png",
	h_p8 : "res/img/powers/8.png",
	h_p9 : "res/img/powers/9.png",
	h_p10 : "res/img/powers/10.png",
	h_p11 : "res/img/powers/11.png",
	h_p12 : "res/img/powers/12.png",
	h_p13 : "res/img/powers/13.png",
	h_p14 : "res/img/powers/14.png",
	h_p15 : "res/img/powers/15.png",
	h_p16 : "res/img/powers/16.png",
	h_p17 : "res/img/powers/17.png",
	h_p18 : "res/img/powers/18.png",
}

var g_ressources = [
    //image
    {type:"image", src:hero_rs.h_m1},
    {type:"image", src:hero_rs.h_m2},
    {type:"image", src:hero_rs.h_m3},
    {type:"image", src:hero_rs.h_m4},
    {type:"image", src:hero_rs.h_m5},
    {type:"image", src:hero_rs.h_m6},
	{type:"image", src:hero_rs.h_p0},
	{type:"image", src:hero_rs.h_p1},
	{type:"image", src:hero_rs.h_p2},
	{type:"image", src:hero_rs.h_p3},
	{type:"image", src:hero_rs.h_p4},
	{type:"image", src:hero_rs.h_p5},
	{type:"image", src:hero_rs.h_p6},
	{type:"image", src:hero_rs.h_p7},
	{type:"image", src:hero_rs.h_p8},
	{type:"image", src:hero_rs.h_p9},
	{type:"image", src:hero_rs.h_p10},
	{type:"image", src:hero_rs.h_p11},
	{type:"image", src:hero_rs.h_p12},
	{type:"image", src:hero_rs.h_p13},
	{type:"image", src:hero_rs.h_p14},
	{type:"image", src:hero_rs.h_p15},
	{type:"image", src:hero_rs.h_p16},
	{type:"image", src:hero_rs.h_p17},
	{type:"image", src:hero_rs.h_p18},
];
