var hero_rs = {
	h_m1 : "res/img/1.png",
	h_m2 : "res/img/2.png",
	h_m3 : "res/img/3.png",
	h_m4 : "res/img/4.png",
	h_m5 : "res/img/5.png",
	h_m6 : "res/img/6.png",
	h_p0 : "res/img/powers/0.png",
	h_p1 : "res/img/powers/1.png",
	h_p2 : "res/img/powers/2.png",
	h_p3 : "res/img/powers/3.png",
	h_p4 : "res/img/powers/4.png",
	h_p5 : "res/img/powers/5.png",
	h_p6 : "res/img/powers/6.png",
	h_p7 : "res/img/powers/7.png",
	h_p8 : "res/img/powers/8.png",
	h_p9 : "res/img/powers/9.png",
	h_p10 : "res/img/powers/10.png",
	h_p11 : "res/img/powers/11.png",
	h_p12 : "res/img/powers/12.png",
	h_p13 : "res/img/powers/13.png",
	h_p14 : "res/img/powers/14.png",
	h_p15 : "res/img/powers/15.png",
	h_p16 : "res/img/powers/16.png",
	h_p17 : "res/img/powers/17.png",
	h_p18 : "res/img/powers/18.png",
	//Customization
	c_arm1 : "res/img/monster/mon_arms/forearm_0.png",
	c_arm2 : "res/img/monster/mon_arms/forearm_a.png",
	c_arm3 : "res/img/monster/mon_arms/hand_0_0.png",
	c_arm4 : "res/img/monster/mon_arms/hand_a_0.png",
	c_arm5 : "res/img/monster/mon_arms/shoulder_0.png",
	c_arm6 : "res/img/monster/mon_arms/shoulder_a.png",
	c_head1: "res/img/monster/mon_head/head_0.png",
	c_head2: "res/img/monster/mon_head/head_1.png",
	c_head3: "res/img/monster/mon_head/head_2.png",
	c_head4: "res/img/monster/mon_head/head_3.png",
	c_leg1 : "res/img/monster/mon_legs/foot_0.png",
	c_leg2 : "res/img/monster/mon_legs/foot_a.png",
	c_leg3 : "res/img/monster/mon_legs/pelvis_0.png",
	c_leg4 : "res/img/monster/mon_legs/thigh_0.png",
	c_leg5 : "res/img/monster/mon_legs/thigh_a.png",
   c_torso1: "res/img/monster/mon_torso/torso_0.png",
	//Customization Menu tool
	c_item1 : "res/img/customization/item1.png",
	c_item2 : "res/img/customization/item2.png",
	c_item3 : "res/img/customization/itemSelected.png",
	c_item4 : "res/img/customization/helmet.png",
	c_item5 : "res/img/customization/weapon.png",
	//Main Menu bar
	m_1 : "res/img/buttons/1.png",
	m_2 : "res/img/buttons/2.png",
	m_3 : "res/img/buttons/3.png",
	m_4 : "res/img/buttons/4.png",
	m_5 : "res/img/buttons/5.png",
	//heroes
	h_1 : "res/img/heroes/emma/emma.png",
	//effects
	e_1 : "res/img/effects/explosion.png",
	e_2 : "res/img/effects/claw.png",
	//plist
	p_1 : "res/img/effects/explosion.plist",
	p_2 : "res/img/heroes/emma/emma.plist",
	p_3 : "res/img/effects/claw.plist",
	//sound
	s_1 : "res/sound/fireImpact",
	s_2 : "res/sound/explodeEffect",
	s_3 : "res/sound/fire",
	s_4 : "res/sound/ice",
	s_5 : "res/sound/shock",
	s_6 : "res/sound/death",
	
}

var g_ressources = [
    //image
    {type:"image", src:hero_rs.h_m1},
    {type:"image", src:hero_rs.h_m2},
    {type:"image", src:hero_rs.h_m3},
    {type:"image", src:hero_rs.h_m4},
    {type:"image", src:hero_rs.h_m5},
    {type:"image", src:hero_rs.h_m6},
	{type:"image", src:hero_rs.h_p0},
	{type:"image", src:hero_rs.h_p1},
	{type:"image", src:hero_rs.h_p2},
	{type:"image", src:hero_rs.h_p3},
	{type:"image", src:hero_rs.h_p4},
	{type:"image", src:hero_rs.h_p5},
	{type:"image", src:hero_rs.h_p6},
	{type:"image", src:hero_rs.h_p7},
	{type:"image", src:hero_rs.h_p8},
	{type:"image", src:hero_rs.h_p9},
	{type:"image", src:hero_rs.h_p10},
	{type:"image", src:hero_rs.h_p11},
	{type:"image", src:hero_rs.h_p12},
	{type:"image", src:hero_rs.h_p13},
	{type:"image", src:hero_rs.h_p14},
	{type:"image", src:hero_rs.h_p15},
	{type:"image", src:hero_rs.h_p16},
	{type:"image", src:hero_rs.h_p17},
	{type:"image", src:hero_rs.h_p18},
	//Customization
	{type:"image", src:hero_rs.c_arm1},
	{type:"image", src:hero_rs.c_arm2},
	{type:"image", src:hero_rs.c_arm3},
	{type:"image", src:hero_rs.c_arm4},
	{type:"image", src:hero_rs.c_arm5},
	{type:"image", src:hero_rs.c_arm6},
	{type:"image", src:hero_rs.c_head1},
	{type:"image", src:hero_rs.c_head2},
	{type:"image", src:hero_rs.c_head3},
	{type:"image", src:hero_rs.c_head4},
	{type:"image", src:hero_rs.c_leg1},
	{type:"image", src:hero_rs.c_leg2},
	{type:"image", src:hero_rs.c_leg3},
	{type:"image", src:hero_rs.c_leg4},
	{type:"image", src:hero_rs.c_leg5},
	{type:"image", src:hero_rs.c_torso1},
	//Customization Menu tool
	{type:"image", src:hero_rs.c_item1},
	{type:"image", src:hero_rs.c_item2},
	{type:"image", src:hero_rs.c_item3},
	{type:"image", src:hero_rs.c_item4},
	{type:"image", src:hero_rs.c_item5},
	// Main Menu bar
    {type:"image", src:hero_rs.m_1},
	{type:"image", src:hero_rs.m_2},
	{type:"image", src:hero_rs.m_3},
	{type:"image", src:hero_rs.m_4},
	{type:"image", src:hero_rs.m_5},
	//heroes
	{type:"image", src:hero_rs.h_1},
	//effects
	{type:"image", src:hero_rs.e_1},
	{type:"image", src:hero_rs.e_2},
	//plist
	{type:"plist", src:hero_rs.p_1},
	{type:"plist", src:hero_rs.p_2},
	{type:"plist", src:hero_rs.p_3},
    //sound
	{type:"effect", src:hero_rs.s_1},
	{type:"effect", src:hero_rs.s_2},
	{type:"effect", src:hero_rs.s_3},
	{type:"effect", src:hero_rs.s_4},
	{type:"effect", src:hero_rs.s_5},
	{type:"effect", src:hero_rs.s_6},
	//fnt

    //tmx

    //bgm

    
];
