var hero_rs = {
	h_m1 : "res/img/1.png",
	h_m2 : "res/img/2.png",
	h_m3 : "res/img/3.png",
	h_m4 : "res/img/4.png",
	h_m5 : "res/img/5.png",
	h_m6 : "res/img/6.png",
	h_p0 : "res/img/powers/0.png",
	h_p1 : "res/img/powers/1.png",
	h_p2 : "res/img/powers/2.png",
	h_p3 : "res/img/powers/3.png",
	h_p4 : "res/img/powers/4.png",
	h_p5 : "res/img/powers/5.png",
	h_p6 : "res/img/powers/6.png",
	h_p7 : "res/img/powers/7.png",
	h_p8 : "res/img/powers/8.png",
	h_p9 : "res/img/powers/9.png",
	h_p10 : "res/img/powers/10.png",
	h_p11 : "res/img/powers/11.png",
	h_p12 : "res/img/powers/12.png",
	h_p13 : "res/img/powers/13.png",
	h_p14 : "res/img/powers/14.png",
	h_p15 : "res/img/powers/15.png",
	h_p16 : "res/img/powers/16.png",
	h_p17 : "res/img/powers/17.png",
	h_p18 : "res/img/powers/18.png",
<<<<<<< HEAD
=======
	//Background
	bg_desert_day: "res/img/background/day.png",
	bg_desert_night: "res/img/background/night.png",
	bg_night_cloud : "res/img/background/night_clouds.png",
>>>>>>> Spriter
	//Customization
	c_arm0 : "res/img/monster/mon_arms/shoulder_a.png",
	c_arm1 : "res/img/monster/mon_arms/forearm_a.png",
	c_arm2: "res/img/monster/mon_arms/hand_a_1.png",
	c_arm3 : "res/img/monster/mon_arms/shoulder_0.png",
	c_arm4 : "res/img/monster/mon_arms/forearm_0.png",
	c_arm5 : "res/img/monster/mon_arms/hand_0_0.png",
	c_arm6 : "res/img/monster/mon_arms/hand_a_0.png",
	c_arm7 : "res/img/monster/mon_arms/hand_0_1.png",
	c_arm8 : "res/img/monster/mon_arms/hand_0_2.png",
	c_arm9 : "res/img/monster/mon_arms/hand_0_3.png",
	c_arm10: "res/img/monster/mon_arms/hand_a_2.png",
	c_arm11: "res/img/monster/mon_arms/hand_a_3.png",
	c_head0: "res/img/monster/mon_head/head_2.png",
	c_head1: "res/img/monster/mon_head/head_3.png",
	c_head2: "res/img/monster/mon_head/head_1.png",
	c_head3: "res/img/monster/mon_head/head_0.png",
	c_leg0 : "res/img/monster/mon_legs/foot_a.png",
	c_leg1 : "res/img/monster/mon_legs/thigh_a.png",
	c_leg2 : "res/img/monster/mon_legs/pelvis_0.png",
	c_leg3 : "res/img/monster/mon_legs/foot_0.png",
	c_leg4 : "res/img/monster/mon_legs/thigh_0.png",
   c_torso0: "res/img/monster/mon_torso/torso_0.png",
   c_shadow0: "res/img/monster/mon_shadows/shadow_idle.png",
	//Assassin images
	c_dagger0 : "res/img/assassin/dagger/10.png",
	c_dagger1 : "res/img/assassin/dagger/09.png",
	c_dagger2 : "res/img/assassin/dagger/07.png",
	c_dagger3 : "res/img/assassin/dagger/08.png",
	c_dagger4 : "res/img/assassin/dagger/14.png",
	c_dagger5 : "res/img/assassin/dagger/04.png",
	c_dagger6 : "res/img/assassin/dagger/11.png",
	c_dagger7 : "res/img/assassin/dagger/03.png",
	c_dagger8 : "res/img/assassin/dagger/15.png",
	c_dagger9 : "res/img/assassin/dagger/05.png",
	c_dagger10: "res/img/assassin/dagger/01.png",
	c_dagger11: "res/img/assassin/dagger/12.png",
	c_dagger12: "res/img/assassin/dagger/13.png",
	c_dagger_spriter:"res/img/assassin/dagger/dagger_assassin.SCML",
	
	//Customization Menu tool
	c_item1 : "res/img/customization/item1.png",
	c_item2 : "res/img/customization/item2.png",
	c_item3 : "res/img/customization/itemSelected.png",
	c_item4 : "res/img/customization/helmet.png",
	c_item5 : "res/img/customization/weapon.png",
	//Main Menu bar
	m_1 : "res/img/buttons/1.png",
	m_2 : "res/img/buttons/2.png",
	m_3 : "res/img/buttons/3.png",
	m_4 : "res/img/buttons/4.png",
	m_5 : "res/img/buttons/5.png",
	//heroes
	h_1 : "res/img/heroes/emma/emma.png",
	//effects
	e_1 : "res/img/effects/explosion.png",
	e_2 : "res/img/effects/claw.png",
	//plist
	p_1 : "res/img/effects/explosion.plist",
	p_2 : "res/img/heroes/emma/emma.plist",
	p_3 : "res/img/effects/claw.plist",
	//sound
	s_1 : "res/sound/fireImpact",
	s_2 : "res/sound/explodeEffect",
	s_3 : "res/sound/fire",
	s_4 : "res/sound/ice",
	s_5 : "res/sound/shock",
	s_6 : "res/sound/death",
	//animation
	a_1 : "res/img/monster/monster.SCML",
	a_2 : "res/img/line0.png",
	a_3 : "res/img/line1.png",
	//hp
	hp : "res/img/buttons/hp.png",
	stamina : "res/img/buttons/stamina.png",
}

var g_ressources = [
    //image
    {type:"image", src:hero_rs.h_m1},
    {type:"image", src:hero_rs.h_m2},
    {type:"image", src:hero_rs.h_m3},
    {type:"image", src:hero_rs.h_m4},
    {type:"image", src:hero_rs.h_m5},
    {type:"image", src:hero_rs.h_m6},
	{type:"image", src:hero_rs.h_p0},
	{type:"image", src:hero_rs.h_p1},
	{type:"image", src:hero_rs.h_p2},
	{type:"image", src:hero_rs.h_p3},
	{type:"image", src:hero_rs.h_p4},
	{type:"image", src:hero_rs.h_p5},
	{type:"image", src:hero_rs.h_p6},
	{type:"image", src:hero_rs.h_p7},
	{type:"image", src:hero_rs.h_p8},
	{type:"image", src:hero_rs.h_p9},
	{type:"image", src:hero_rs.h_p10},
	{type:"image", src:hero_rs.h_p11},
	{type:"image", src:hero_rs.h_p12},
	{type:"image", src:hero_rs.h_p13},
	{type:"image", src:hero_rs.h_p14},
	{type:"image", src:hero_rs.h_p15},
	{type:"image", src:hero_rs.h_p16},
	{type:"image", src:hero_rs.h_p17},
	{type:"image", src:hero_rs.h_p18},
<<<<<<< HEAD
=======
	//Background
	{type:"image", src:hero_rs.bg_desert_day},
	{type:"image", src:hero_rs.bg_desert_night},
	{type:"image", src:hero_rs.bg_night_cloud},
>>>>>>> Spriter
	//Customization
	{type:"image", src:hero_rs.c_arm0},
	{type:"image", src:hero_rs.c_arm1},
	{type:"image", src:hero_rs.c_arm2},
	{type:"image", src:hero_rs.c_arm3},
	{type:"image", src:hero_rs.c_arm4},
	{type:"image", src:hero_rs.c_arm5},
	{type:"image", src:hero_rs.c_arm6},
	{type:"image", src:hero_rs.c_arm7},
	{type:"image", src:hero_rs.c_arm8},
	{type:"image", src:hero_rs.c_arm9},
	{type:"image", src:hero_rs.c_arm10},
	{type:"image", src:hero_rs.c_arm11},
	{type:"image", src:hero_rs.c_head0},
	{type:"image", src:hero_rs.c_head1},
	{type:"image", src:hero_rs.c_head2},
	{type:"image", src:hero_rs.c_head3},
	{type:"image", src:hero_rs.c_leg0},
	{type:"image", src:hero_rs.c_leg1},
	{type:"image", src:hero_rs.c_leg2},
	{type:"image", src:hero_rs.c_leg3},
	{type:"image", src:hero_rs.c_leg4},
	{type:"image", src:hero_rs.c_torso0},
	{type:"image", src:hero_rs.c_shadow0},
	//Assassin images
	
	{type:"image", src:hero_rs.c_dagger0},
	{type:"image", src:hero_rs.c_dagger1},
	{type:"image", src:hero_rs.c_dagger2},
	{type:"image", src:hero_rs.c_dagger3},
	{type:"image", src:hero_rs.c_dagger4},
	{type:"image", src:hero_rs.c_dagger5},
	{type:"image", src:hero_rs.c_dagger6},
	{type:"image", src:hero_rs.c_dagger7},
	{type:"image", src:hero_rs.c_dagger8},
	{type:"image", src:hero_rs.c_dagger9},
	{type:"image", src:hero_rs.c_dagger10},
	{type:"spriter", src:hero_rs.c_dagger_spriter},
	
	//Customization Menu tool
	{type:"image", src:hero_rs.c_item1},
	{type:"image", src:hero_rs.c_item2},
	{type:"image", src:hero_rs.c_item3},
	{type:"image", src:hero_rs.c_item4},
	{type:"image", src:hero_rs.c_item5},
	// Main Menu bar
    {type:"image", src:hero_rs.m_1},
	{type:"image", src:hero_rs.m_2},
	{type:"image", src:hero_rs.m_3},
	{type:"image", src:hero_rs.m_4},
	{type:"image", src:hero_rs.m_5},
	//heroes
	{type:"image", src:hero_rs.h_1},
	//effects
	{type:"image", src:hero_rs.e_1},
	{type:"image", src:hero_rs.e_2},
	//plist
	{type:"plist", src:hero_rs.p_1},
	{type:"plist", src:hero_rs.p_2},
	{type:"plist", src:hero_rs.p_3},
    //sound
	{type:"effect", src:hero_rs.s_1},
	{type:"effect", src:hero_rs.s_2},
	{type:"effect", src:hero_rs.s_3},
	{type:"effect", src:hero_rs.s_4},
	{type:"effect", src:hero_rs.s_5},
	{type:"effect", src:hero_rs.s_6},
	//fnt

    //tmx

    //bgm
	
	//animation
	{type:"spriter", src:hero_rs.a_1},
    {type:"image", src:hero_rs.a_2},
	{type:"image", src:hero_rs.a_3},
	//hp
	{type:"image", src:hero_rs.hp},
	{type:"image", src:hero_rs.stamina},
];
